
package br.com.esocial.webservice.producaorestrita.envioLote;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServicoEnviarLoteEventos", targetNamespace = "http://www.esocial.gov.br/servicos/empregador/lote/eventos/envio/v1_1_0", wsdlLocation = "file:/D:/Esocial/ws/envioLote/WsEnviarLoteEventos.wsdl")
public class ServicoEnviarLoteEventos_Service
    extends Service
{

    private final static URL SERVICOENVIARLOTEEVENTOS_WSDL_LOCATION;
    private final static WebServiceException SERVICOENVIARLOTEEVENTOS_EXCEPTION;
    private final static QName SERVICOENVIARLOTEEVENTOS_QNAME = new QName("http://www.esocial.gov.br/servicos/empregador/lote/eventos/envio/v1_1_0", "ServicoEnviarLoteEventos");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
        	url = new URL("file:"+System.getProperty("user.dir")+"/WsEnviarLoteEventos.wsdl");
//        	 url = new URL("file:/D:/Esocial/workspace_assinaturas/envioLote/WsEnviarLoteEventos.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICOENVIARLOTEEVENTOS_WSDL_LOCATION = url;
        SERVICOENVIARLOTEEVENTOS_EXCEPTION = e;
    }

    public ServicoEnviarLoteEventos_Service() {
        super(__getWsdlLocation(), SERVICOENVIARLOTEEVENTOS_QNAME);
    }

    public ServicoEnviarLoteEventos_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICOENVIARLOTEEVENTOS_QNAME, features);
    }

    public ServicoEnviarLoteEventos_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICOENVIARLOTEEVENTOS_QNAME);
    }

    public ServicoEnviarLoteEventos_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICOENVIARLOTEEVENTOS_QNAME, features);
    }

    public ServicoEnviarLoteEventos_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicoEnviarLoteEventos_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServicoEnviarLoteEventos
     */
    @WebEndpoint(name = "WsEnviarLoteEventos")
    public ServicoEnviarLoteEventos getWsEnviarLoteEventos() {
        return super.getPort(new QName("http://www.esocial.gov.br/servicos/empregador/lote/eventos/envio/v1_1_0", "WsEnviarLoteEventos"), ServicoEnviarLoteEventos.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicoEnviarLoteEventos
     */
    @WebEndpoint(name = "WsEnviarLoteEventos")
    public ServicoEnviarLoteEventos getWsEnviarLoteEventos(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.esocial.gov.br/servicos/empregador/lote/eventos/envio/v1_1_0", "WsEnviarLoteEventos"), ServicoEnviarLoteEventos.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICOENVIARLOTEEVENTOS_EXCEPTION!= null) {
            throw SERVICOENVIARLOTEEVENTOS_EXCEPTION;
        }
        return SERVICOENVIARLOTEEVENTOS_WSDL_LOCATION;
    }

}
