
package br.com.esocial.webservice.producaorestrita.envioLote;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServicoEnviarLoteEventos", targetNamespace = "http://www.esocial.gov.br/servicos/empregador/lote/eventos/envio/v1_1_0")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicoEnviarLoteEventos {


    /**
     * 
     * @param loteEventos
     * @return
     *     returns com.atlantic.esocial.envioLote.EnviarLoteEventosResponse.EnviarLoteEventosResult
     */
    @WebMethod(operationName = "EnviarLoteEventos", action = "http://www.esocial.gov.br/servicos/empregador/lote/eventos/envio/v1_1_0/ServicoEnviarLoteEventos/EnviarLoteEventos")
    @WebResult(name = "EnviarLoteEventosResult", targetNamespace = "http://www.esocial.gov.br/servicos/empregador/lote/eventos/envio/v1_1_0")
    @RequestWrapper(localName = "EnviarLoteEventos", targetNamespace = "http://www.esocial.gov.br/servicos/empregador/lote/eventos/envio/v1_1_0", className = "com.atlantic.esocial.envioLote.EnviarLoteEventos")
    @ResponseWrapper(localName = "EnviarLoteEventosResponse", targetNamespace = "http://www.esocial.gov.br/servicos/empregador/lote/eventos/envio/v1_1_0", className = "com.atlantic.esocial.envioLote.EnviarLoteEventosResponse")
    public br.com.esocial.webservice.producaorestrita.envioLote.EnviarLoteEventosResponse.EnviarLoteEventosResult enviarLoteEventos(
        @WebParam(name = "loteEventos", targetNamespace = "http://www.esocial.gov.br/servicos/empregador/lote/eventos/envio/v1_1_0")
        br.com.esocial.webservice.producaorestrita.envioLote.EnviarLoteEventos.LoteEventos loteEventos);

}
