
package br.com.esocial.webservice.producaorestrita.consultarLote;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServicoConsultarLoteEventos", targetNamespace = "http://www.esocial.gov.br/servicos/empregador/lote/eventos/envio/consulta/retornoProcessamento/v1_1_0")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicoConsultarLoteEventos {


    /**
     * 
     * @param consulta
     * @return
     *     returns com.atlantic.esocial.consultaLote.ConsultarLoteEventosResponse.ConsultarLoteEventosResult
     */
    @WebMethod(operationName = "ConsultarLoteEventos", action = "http://www.esocial.gov.br/servicos/empregador/lote/eventos/envio/consulta/retornoProcessamento/v1_1_0/ServicoConsultarLoteEventos/ConsultarLoteEventos")
    @WebResult(name = "ConsultarLoteEventosResult", targetNamespace = "http://www.esocial.gov.br/servicos/empregador/lote/eventos/envio/consulta/retornoProcessamento/v1_1_0")
    @RequestWrapper(localName = "ConsultarLoteEventos", targetNamespace = "http://www.esocial.gov.br/servicos/empregador/lote/eventos/envio/consulta/retornoProcessamento/v1_1_0", className = "com.atlantic.esocial.consultaLote.ConsultarLoteEventos")
    @ResponseWrapper(localName = "ConsultarLoteEventosResponse", targetNamespace = "http://www.esocial.gov.br/servicos/empregador/lote/eventos/envio/consulta/retornoProcessamento/v1_1_0", className = "com.atlantic.esocial.consultaLote.ConsultarLoteEventosResponse")
    public br.com.esocial.webservice.producaorestrita.consultarLote.ConsultarLoteEventosResponse.ConsultarLoteEventosResult consultarLoteEventos(
        @WebParam(name = "consulta", targetNamespace = "http://www.esocial.gov.br/servicos/empregador/lote/eventos/envio/consulta/retornoProcessamento/v1_1_0")
        br.com.esocial.webservice.producaorestrita.consultarLote.ConsultarLoteEventos.Consulta consulta);

}
